version: "3.5"

networks:
  nodejs-test-network:
    driver: bridge

services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: nodejstest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d rinha" ]
      interval: 5s
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
